# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A Gibbs sampler using Rcpp
#' @description A Gibbs sampler using Rcpp
#' @param x0 float, first component of the start point
#' @param y0 float, second component of the start point
#' @param n int, the number of samples to be generated
#' @return a matrix of shape n*2, 
#' @examples
#' \dontrun{
#' GibbsC(0,0,1000)
#' }
#' @export
GibbsC <- function(x0, y0, n) {
    .Call('_StatComp22087_GibbsC', PACKAGE = 'StatComp22087', x0, y0, n)
}

